name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SHEET_NAME: WorkTimeTracker
      USERS_SHEET: Users
      ACTIVE_SESSIONS_SHEET: ActiveSessions
      CREDENTIALS_FILE: .creds/service_account.json
      TELEGRAM_SILENT: "1"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Decode service account
        if: ${{ secrets.SERVICE_ACCOUNT_JSON_BASE64 != '' }}
        env:
          SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.SERVICE_ACCOUNT_JSON_BASE64 }}
        run: |
          mkdir -p .creds
          python - <<'PY'
          import os, base64, pathlib
          b64 = os.environ.get("SERVICE_ACCOUNT_JSON_BASE64")
          if b64:
              pathlib.Path(".creds/service_account.json").write_bytes(base64.b64decode(b64))
              print("service_account.json restored")
          else:
              print("No SERVICE_ACCOUNT_JSON_BASE64 secret; skipping.")
          PY

      - name: Compile check
        run: python -m compileall .

      - name: Smoke test
        run: python tools/smoke_ci.py
